// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NtemtemGQL.Data;

namespace NtemtemGQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211006222954_AddTimezoneFieldToAppointmentAndOrganization")]
    partial class AddTimezoneFieldToAppointmentAndOrganization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("NtemtemGQL.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientEmail = "adzamkomla@gmail.com",
                            ClientName = "Komla Adzam",
                            ClientPhone = "0553995074",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 10, 11, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            ExtraInfo = "This meeting is with Dr. Philip Kpone.",
                            OrganizationId = 1,
                            Reason = "This is an appointment to meet the head dematologist.",
                            StartTime = new DateTime(2021, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "SCHEDULED",
                            Timezone = "Africa/Accra",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClientEmail = "adzamkomla.dev@gmail.com",
                            ClientName = "Etorenyo Adzam",
                            ClientPhone = "0553995074",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 10, 7, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            ExtraInfo = "This meeting is with Dr. Anna Kpone.",
                            OrganizationId = 1,
                            Reason = "This is an appointment to meet the head opthalmologist.",
                            StartTime = new DateTime(2021, 10, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "SCHEDULED",
                            Timezone = "Africa/Accra",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClientEmail = "adzamkomla.dev@gmail.com",
                            ClientName = "Etorenyo Adzam",
                            ClientPhone = "0553995074",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2021, 10, 7, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ExtraInfo = "This meeting is with Mr. Godwin Amefia.",
                            OrganizationId = 2,
                            Reason = "This is an appointment to meet the manager of operations of Arkesel.",
                            StartTime = new DateTime(2021, 10, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "SCHEDULED",
                            Timezone = "Africa/Accra",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NtemtemGQL.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Achimota Hospital, Aggrey Street, Achimota",
                            CreatedAt = new DateTime(2021, 10, 6, 22, 29, 54, 111, DateTimeKind.Utc).AddTicks(1603),
                            Description = "Achimota Hospital is a government hospital built to serve the Achimota community.",
                            Email = "adzamkomla.dev@gmail.com",
                            Name = "Achimota Hospital",
                            Phone = "233553995074",
                            Timezone = "Africa/Accra",
                            UpdatedAt = new DateTime(2021, 10, 6, 22, 29, 54, 111, DateTimeKind.Utc).AddTicks(1876)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Arkesel, #1 Nii Oga Street",
                            CreatedAt = new DateTime(2021, 10, 6, 22, 29, 54, 111, DateTimeKind.Utc).AddTicks(2125),
                            Description = "Arkesel is a clouds communication company.",
                            Email = "adzamkomla@gmail.com",
                            Name = "Arkesel Company Limited",
                            Phone = "233202442452",
                            Timezone = "Africa/Accra",
                            UpdatedAt = new DateTime(2021, 10, 6, 22, 29, 54, 111, DateTimeKind.Utc).AddTicks(2127)
                        });
                });

            modelBuilder.Entity("NtemtemGQL.Models.WorkPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("WorkPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Monday",
                            EndTime = "23:00",
                            OrganizationId = 1,
                            StartTime = "02:00"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Tuesday",
                            EndTime = "23:00",
                            OrganizationId = 1,
                            StartTime = "02:00"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Wednesday",
                            EndTime = "23:00",
                            OrganizationId = 1,
                            StartTime = "02:00"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Thursday",
                            EndTime = "23:00",
                            OrganizationId = 1,
                            StartTime = "02:00"
                        },
                        new
                        {
                            Id = 5,
                            Day = "Friday",
                            EndTime = "23:00",
                            OrganizationId = 1,
                            StartTime = "02:00"
                        },
                        new
                        {
                            Id = 6,
                            Day = "Monday",
                            EndTime = "17:00",
                            OrganizationId = 2,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 7,
                            Day = "Tuesday",
                            EndTime = "17:00",
                            OrganizationId = 2,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 8,
                            Day = "Wednesday",
                            EndTime = "17:00",
                            OrganizationId = 2,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 9,
                            Day = "Thursday",
                            EndTime = "14:00",
                            OrganizationId = 2,
                            StartTime = "09:00"
                        });
                });

            modelBuilder.Entity("NtemtemGQL.Models.Appointment", b =>
                {
                    b.HasOne("NtemtemGQL.Models.Organization", "Organization")
                        .WithMany("Appointments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NtemtemGQL.Models.WorkPeriod", b =>
                {
                    b.HasOne("NtemtemGQL.Models.Organization", "Organization")
                        .WithMany("WorkPeriods")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NtemtemGQL.Models.Organization", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorkPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
